# Generated by Django 2.2.5 on 2019-11-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invitation_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_invited',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
    ]
