version: '3'

services:
  appforme_pg:
      image: "kartoza/postgis:9.6-2.4"
      container_name: appforme_pg
      hostname: appforme_pg
      restart: always
      env_file: "./docker/environments"
      ports:
        - "5432:5432"
      volumes:
        - ./appforme_pg:/var/lib/postgresql/9.6/main

  appforme_app:
    container_name: appforme_app
    hostname: appforme_app
    restart: always
    build: ./
    volumes:
      - ./core:/appforme_app/core
      - ./authentication:/appforme_app/authentication
      - ./users:/appforme_app/users
      - ./media:/appforme_app/media
    ports:
      - "8000:8000"
    env_file: "./docker/environments"
    depends_on:
      - appforme_pg

  app_rabbit:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
    volumes:
      - ./app_rabbit_data:/var/lib/rabbitmq

  app_socket_service:
    container_name: app_socket_service
    hostname: app_socket_service
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile-nodejs
    volumes:
      - ./socket_service:/socket_service
    ports:
      - "4000:4000"
    depends_on:
      - app_rabbit
      - appforme_app
    links:
      - app_rabbit
      - appforme_app:appforme

volumes:
  appforme_pg:
  app_rabbit_data:
  media:
